[package]
name = "sms"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version="1.0.130", features=["derive"] }
serde_json = "1.0.67"
chrono = "0.4.19"
toml = "0.5.8"
mysql = "21.0.1"